server:
  port: ${PORT:8090}
  address: 0.0.0.0

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost/auth}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: none
  mail:
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    port: ${MAIL_PORT:587}
    host: ${MAIL_HOST:smtp.gmail.com}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

jwt:
  secret: ${KEYSECRET_SECURITY}
  expiration: ${EXPIRE_DAYS_SECURITY:3600000}

management:
  endpoints:
    web:
      exposure:
        include: "*"
        